title: Not a food blog.
tagline: A digital recipe book—These are some of my favorites along with some new ones I’m just trying out.
sass:
  sass_dir: _sass
  style: compressed
permalink: :categories/:title.html
exclude: [README.md, Rakefile, Gemfile]
