title: Recipe Book
description: A collection of my favorite recipes

markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
baseurl: http://levimcg.github.io/recipe-book/

exclude: [README.md, Rakefile]
