title: Not a food blog.
tagline: A digital recipe book—These are some of my favorite along with some new ones I’m just trying out.
markdown: redcarpet
sass:
  sass_dir: _sass
permalink: :categories/:title.html
exclude: [README.md, Rakefile, Gemfile]
