title: Recipe Book
description: A collection of my favorite recipes

markdown: redcarpet
highlighter: pygments
permalink: /:title
sass:
  sass_dir: _sass
baseurl: http://levimcg.github.io/recipes/

exclude: [README.md, Rakefile]
