title: Recipe Book
description: A collection of my favorite recipes
markdown: redcarpet
sass:
  sass_dir: _sass
# baseurl: /recipe-book
permalink: recipes/:categories/:title.html
exclude: [README.md, Rakefile, Gemfile]
